# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_sw.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1003, 578)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.hpf1Button = QtWidgets.QPushButton(self.centralwidget)
        self.hpf1Button.setGeometry(QtCore.QRect(640, 60, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.hpf1Button.setFont(font)
        self.hpf1Button.setObjectName("hpf1Button")
        self.hpf2Button = QtWidgets.QPushButton(self.centralwidget)
        self.hpf2Button.setGeometry(QtCore.QRect(820, 60, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.hpf2Button.setFont(font)
        self.hpf2Button.setObjectName("hpf2Button")
        self.vsobelButton = QtWidgets.QPushButton(self.centralwidget)
        self.vsobelButton.setGeometry(QtCore.QRect(640, 220, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.vsobelButton.setFont(font)
        self.vsobelButton.setObjectName("vsobelButton")
        self.hsobelButton = QtWidgets.QPushButton(self.centralwidget)
        self.hsobelButton.setGeometry(QtCore.QRect(820, 220, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.hsobelButton.setFont(font)
        self.hsobelButton.setObjectName("hsobelButton")
        self.gaussButton = QtWidgets.QPushButton(self.centralwidget)
        self.gaussButton.setGeometry(QtCore.QRect(730, 310, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gaussButton.setFont(font)
        self.gaussButton.setObjectName("gaussButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(750, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lpf1Button = QtWidgets.QPushButton(self.centralwidget)
        self.lpf1Button.setGeometry(QtCore.QRect(640, 140, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lpf1Button.setFont(font)
        self.lpf1Button.setObjectName("lpf1Button")
        self.lpf2Button = QtWidgets.QPushButton(self.centralwidget)
        self.lpf2Button.setGeometry(QtCore.QRect(820, 140, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lpf2Button.setFont(font)
        self.lpf2Button.setObjectName("lpf2Button")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(210, 490, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 10, 591, 451))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Projekt_SW_PG_SP/basic.png"))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1003, 21))
        self.menubar.setObjectName("menubar")
        self.menu_INFO = QtWidgets.QMenu(self.menubar)
        self.menu_INFO.setObjectName("menu_INFO")
        self.menuPlik = QtWidgets.QMenu(self.menubar)
        self.menuPlik.setObjectName("menuPlik")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOtworz = QtWidgets.QAction(MainWindow)
        self.actionOtworz.setObjectName("actionOtworz")
        self.actionZapisz = QtWidgets.QAction(MainWindow)
        self.actionZapisz.setObjectName("actionZapisz")
        self.menuPlik.addAction(self.actionOtworz)
        self.menuPlik.addAction(self.actionZapisz)
        self.menubar.addAction(self.menuPlik.menuAction())
        self.menubar.addAction(self.menu_INFO.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Filtering - Pawel Gasiewski"))
        self.hpf1Button.setText(_translate("MainWindow", "HPF - slabszy"))
        self.hpf2Button.setText(_translate("MainWindow", "HPF - mocniejszy"))
        self.vsobelButton.setText(_translate("MainWindow", "Sobel - pionowy"))
        self.hsobelButton.setText(_translate("MainWindow", "Sobel - poziomy"))
        self.gaussButton.setText(_translate("MainWindow", "Gaussowski "))
        self.label.setText(_translate("MainWindow", "Rodzaj filtru : "))
        self.lpf1Button.setText(_translate("MainWindow", "LPF - slabszy"))
        self.lpf2Button.setText(_translate("MainWindow", "LPF - mocniejszy"))
        self.pushButton.setText(_translate("MainWindow", "Reset"))
        self.menu_INFO.setTitle(_translate("MainWindow", "-=+ INFO +=-"))
        self.menuPlik.setTitle(_translate("MainWindow", "Plik"))
        self.actionOtworz.setText(_translate("MainWindow", "Otworz"))
        self.actionOtworz.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionZapisz.setText(_translate("MainWindow", "Zapisz"))
        self.actionZapisz.setShortcut(_translate("MainWindow", "Ctrl+S"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

